### ISSUE TITLE
Baseline, acceptable R

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/software_carbon_intensity#117]
As discussed during the working group

key idea:
"What does the software scale by"
(or functional unit)

R:
API call/request (per call)
Benchmark (version) (for lab vs. real-world)
User (account/person/per install/
Machine
Minute (time unit)
Device/Physical site (home, factory, device)
Data volume (bytes through system)
Job (batch jobs, training rounds)
Transaction (payments systems)
Mining
Database read/write

**Comment by Henry-WattTime** [comment]
For future consideration:

Comparability important for standardizing
v2 standard? may move to specific requirements for r for different industries in future revisions
Start optimizing
features of product are different, hard to compare
Useful internally for making decisions
	
If metrics exist
some consumers will make decisions based on intensity
	companies will immediately use nuanced description to differentiate
	to justify why not ranking first

**Comment by Henry-WattTime** [comment]
Henry commenting as Henry:

You all are going to hate me for this, but we know some crypto currency people will want to start using this standard. That means that value might have to be one of the R's?

**Comment by vaughanknight** [comment]
On Crypto - Value ends up being a very indepdendent factor.  And this should be about driving the right behaviour.  If we associate R with value, we encourage making high emissions crypto more valuable to reduce it's SCI, when it actually will drive higher emissions.

It also means lower value crypto with better SCI  but lower valuable will look more desirable.  Whether it's transaction cost + ming cost (i.e. for proof of work crypto, mining carbon is effectively the embodied carbon because if I hold some bitcoin, someone mined that no differently to mining silicon)

For proof of work crypto especially, there would likely need to be an SCI on the creation of a all coins to date/# coins + transaction.  But for proof of stake (greener coins like Cardano), or proof of space-time crypto would have very different profiles.

**Comment by vaughanknight** [comment]
* Mining

**Comment by Henry-WattTime** [comment]
Vaughan, that makes sense. I assume that means it will have to be mining emissions per coin (regardless of the value of that coin). I've added mining to the top list.

Sara, I've added Database Read/Write to the list as well.

**Comment by vaughanknight** [comment]
Henry - yep.  Mining per coin for some coins is going to be 99% of that coins carbon emissions even after a million transactions, and for other coins, the transactions/gas cost might be 99%.  And I feel it's the average mining emissions we should look at.

There is probably also a discussion about the scale of the blockchain footprint in terms of storage ... so many things that can wait for v2.  I think someone could right a decent spec on the various blockchain technologies/approaches that then would apply across all blockchain which could encompass crypto, consortiums, etc.

**Comment by vaughanknight** [comment]
This raises an interesting point - We don't know where the coins are mined.  This is possibly another issue that I'm happy to create.

For software that runs globally distributed and at different times, the emissions value will change due to the emissions in the energy being consumed.  How does SCI work here for the developer (vs the operator) of software?  Calculating the energy consumed is a complex thing on it's own, but that consumption is distributed across a global energy profile not in control of the developer, and predominantly where energy is cheap (and emissions unaware).   Microsoft may know where Windows is being run globally, so can calculate this, but for a lot of software (especially open source) this is not known.

This is likely a separate issue (and maybe it exists) but do we have a nominal rating for software that can run anywhere on the planet?  If I write the next crypto, or tensorflow, what is the gcO2eq/kWh value I use to calculate the SCI?  If I live in New Zealand it's ~0g, if I live in Sydney it's ~1000g, but the software runs everywhere.  I need to do another scan of the document to see if I've missed it.
