### ISSUE TITLE
Consider Power Usage Effectiveness (PUE)

### ISSUE THREAD

**Issue by Green-Software** [Green-Software-Foundation/software_carbon_intensity#176]
The Power Usage Effectiveness (PUE) is not included as part of the operational energy. The total operational energy includes the energy consumed by the computing equipment and the supporting energy consumed by facilities (e.g. HVAC).

PUE is the ratio of total amount of energy used by a computer data center facility to the energy used by the computing equipment. If we do not include PUE, a software running at the same hardware with the same energy consumption at two different datacenters located in the same city would have the same operational energy E based on the current equation. However, if datacenter A's PUE is 1.1 while datacenter B's PUE is 1.3, the actual total energy consumption of the same software running at these two data centers would be 18% different. That difference is not reflected by the current equation.

If we consider PUE, the equation would be: SCI = ((E * PUE * I) + M) per R 

Note that there are three potential issues if we do consider PUE: (1) PUE varies by seasons. Should we use the lowest PUE or average yearly measured PUEs? (2) Large data centers (e.g. Microsoft, Google, and Facebook) monitor PUEs frequently but PUE may not be widely available in other small scale systems. Including PUE in SCI will motivate more data centers to measure and improve their PUEs. (3) If we include PUE in the equation, SCI score could be lowered without optimizing code but by optimizing facility operation or moving software to a facility with lower PUE. In general, it is still a good thing to encourage, just like we encourage software to run in a location with low carbon intensity.

**Comment by Henry-WattTime** [comment]
Oh I like this a lot!

**Comment by jawache** [comment]
That's a good point, we should make a reference to it in the energy section to include the PUE in your calculation when running in the cloud, but since the equation has to be applicable to non-cloud scenarios including it in the main equation would be confusing. I would suggest just discussing it in the `E` section. 

As far as I am aware I don't believe any cloud provider gives the PUE at the DC level, I believe all the major players either give a global yearly average or don't discuss it at all? I could be wrong about that, I know it's true for Microsoft.
