### ISSUE TITLE
Badge for Conformance

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#24]
"Conformance" for the SCI
- Should there be different badges for different levels of conformance with the SCI?

**Comment by atg-abhishek** [comment]
Indeed @Henry-WattTime - I think it almost needs something like a certificate-granting authority which could be a sub-WG of the Standards WG so that we can manage how that process manifests?

**Comment by jawache** [comment]
This is a very valid point and something we defo should explore, it would be outside the scope of the Standards WG through I think, possibly under Trademark depending on how we want to structure it? I would not mention it in the spec.

**Comment by mrchrisadams** [comment]
Hey folk, my understanding was that this is why there is a trademark group - you use trademark to exert some degree of control over how people might use a name, or marque, or logo.

There's an initial (tiny) PR here, with some examples of how people use trademark too. I'll add the links to Microsoft's own guidance, as they use a combination of trademark law and specific contracts with partners. 

This initial file here is a readable outline of what you use typically trademark for and why you have it:

https://github.com/Green-Software-Foundation/trademark_policy/blob/371236467152e0a14c50d9a9f80812dd3dac5518/Trademark_policy/Trademark_policy_White_Paper.md

For the next trademark WG meeting, we'll be discussing in more detail, because we want to be able to refer to the work going on in software intensity - and ideally in the future there being some way to make claims that can be audited - leaving room for either certification or some other way to create trust.

If you have specific thoughts, I'll keep an eye on this issue, but please consider adding something to this issue here as well:

https://github.com/Green-Software-Foundation/trademark_policy/issues/5

**Comment by atg-abhishek** [comment]
Sounds good and agreed @jawache and @mrchrisadams - I'll be joining in on the TWG as well so that there is visibility. I'll close this issue so that we can have discussions on this in the TWG repo.
