### ISSUE TITLE
Request to use uniform wording across the doc 

### ISSUE THREAD

**Issue by varnepalli1** [Green-Software-Foundation/software_carbon_intensity#276]
For example, under section  "Procedure", used "Software Component" and "functional unit". Do they refer to same in the given context or differ? If those are same, it would be nice to use either one of the words at all the places. Otherwise, give better clarity on the differences and the context of application

**Comment by atg-abhishek** [comment]
They are both different @varnepalli1 - the functional unit refers to how the software system scales (e.g. # of users) while the software component is a piece comprising the software system such as a database. So, we will retain the wording as is and hopefully this clarifies the difference between them. 

Also, as a note, I observed that you've raised a few issues on this repo. If you have questions related to the SCI, we encourage the creation of [discussion](https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions) topics rather than issues. Thanks!
