### ISSUE TITLE
Characteristic: Consequential versus Attributional

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/software_carbon_intensity#3]

**Comment by atg-abhishek** [comment]
I agree with this @jawache - my inclination would be to make it as _close to reality_ as possible thus strengthening both its **applicability** and **actionability** - key characteristics if we want to trigger behaviour change on the end of the people who will be consuming this in the first place.

**Comment by Henry-WattTime** [comment]
Yes, this is exactly the issue we are grappling with. We are also careful to frame it as a measuring the impact of creating that product, not the footprint of the organization. This post contains a discussion that might be a useful starting point: https://ghginstitute.org/2021/04/21/the-most-important-ghg-accounting-concept-you-may-not-have-heard-of-the-attributional-consequential-distinction/

Another note. It is possible to measure average emissions in a granular sense (hourly for a specific grid region) but that still does not describe the impact of choosing to consume electricity. Which is why we would recommend using a marginal factor to make decisions.

**Comment by jawache** [comment]
Great point @atg-abhishek. I really like that interpretation of consequential, it's about triggering a behaviour change that reduces a number.

This is a great explanation of something I've been grappling with for a while, the obsessive calculation of a number (attribution) vs. information you need in order to make good decisions (consequential).

I suppose that's also the thing about this number, this number we want to calculate is information. If it's useful information it will trigger action. If it's not useful it won't.

Specifically, If we are choosing consequential we are saying that **it won't sum up**. Adding up all the software emissions from a company using our consequential methodology will NOT sum up to the same number a company calculates using the attributional model.

**Comment by jawache** [comment]
Oh and another point, does this mean that to be consequential we need to ignore the total carbon emissions? 

E.g. For the energy space, the consequential emissions would be the marginal carbon intensity. If you were to consume one more kWh right now, this is the carbon emissions you would be responsible for emitting because this specific power plant would have to ramp up.

If we were to apply this to the software space, then perhaps the question we might try to answer is. If the application was to get one more user this is the carbon emissions that that additional user would be responsible for emitting. Based on the additional hardware, energy costs and the current marginal carbon intensity.

The software marginal carbon intensity would also vary then by region and by time, just like electrical marginal carbon intensity.

Interestingly also I think it means that we can skip calculating the total carbon emissions for an application. We can just look at the incremental change from adding **one more user** which I think is a much more narrowly targetted question and can be more easily answered.

**Comment by atg-abhishek** [comment]
This resonates quite a bit with me @jawache !

> Specifically, If we are choosing consequential we are saying that **it won't sum up**. Adding up all the software emissions from a company using our consequential methodology will NOT sum up to the same number a company calculates using the attributional model. 

Perhaps when we're thinking along these lines, the consideration is one of empowerment. That is, if we overburden the person's action with things that they can't control in the choice window that they have, we are disincentivizing behavior change because they will be paralyzed with information they can't act on.

**Comment by atg-abhishek** [comment]
You know now that you mention this @jawache

>Interestingly also I think it means that we can skip calculating the total carbon emissions for an application. We can just look at the incremental change from adding one more user which I think is a much more narrowly targetted question and can be more easily answered.

It is not only more well-defined and **computable**, but also something that I believe will resonate more with the developers, PMs, etc. when they communicate this to their SLT and other stakeholders who are charged with utilizing these metrics in the first place.

**Comment by jawache** [comment]
Is a "rate" always consequential? 

I mean according to the meaning of the word, it will tell me what the consequences are of a decision.

If my software carbon intensity is 10g / user. I know my next user will add 10g of carbon, so that's consequential, right?

Also there is this non-linear/linear relationship question as well I think. For most software, will the carbon intensity be linear? E.g. will it be 10g / user, for every user? If not, what are the non-linear aspects that will creep in and are they important to account for?

For electricity the marginal carbon intensity is non-linear, for every additional kWh there might be a different amount of carbon emissions. I'm not sure how this relates to the characteristic just thinking openly.

**Comment by atg-abhishek** [comment]
So you make an interesting point @jawache ,in fact, I'd be shocked if the rate wasn't non-linear since the underlying mechanics are. More than a rate then perhaps we should be thinking of a **model** given some expected traffic pattern. This way, the end consumer can clearly see points of inflection and explore re-architecting the solution if need be when they hit a part of the curve that exacerbates their marginal carbon emissions.

**Comment by atg-abhishek** [comment]
Remaining things to be addressed moved to Issue #17
