### ISSUE TITLE
Methodology For Energy Consumption (`E`)

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/software_carbon_intensity#40]
This is a can of worms, but I'm flagging this so we can puzzle through fun questions such as how we account for.... 

- Shared hardware? @SaraEmilyBergman has a great point here
- idle load? 
- Utilization/energy consumption relationship
- Acceptable ways to measure and report energy consumption 

All software-based energy measurement contains errors. In terms of methodology, we have two approaches that may need to meet somewhere in the middle 
- top-down (e.g. datacenter plug)
- bottom-up (on-chip) libraries (e.g. NVIDIA-smi or DCGM libraries) [have been shown to have between 8-73% error](https://tel.archives-ouvertes.fr/tel-02948725/document/)

### ****Modeling**** 
- if everything is a model, what are the requirements? Some examples:
- e.g. mapping utilization to energy per lookup table provided by hardware companies 
- what are the boundaries of your software model ?per @vaughanknight. - Can't just give a number and not account for software boundary #56. The boundary needs guidance on what significance means, **including supporting network infrastructure such as:** 
- idle machines
- data stack
- supporting network infrastructure 
- Compte
- Storage
- Networking
- Memory

per @SaraEmilyBergman, we should add fundamental constraints/guardrails:
- power consumption can't exceed the input power

**Comment by SaraEmilyBergman** [comment]
A can of worms indeed but a very interesting one! I have previously written a little of this topic on [Microsoft's SSE blog](https://devblogs.microsoft.com/sustainable-software/how-to-measure-the-power-consumption-of-your-backend-service/#what-if-i-run-in-the-cloud), especially on how one can guesstimate without having insights into energy metrics.
I agree with software-based metrics not being an ideal approach.

I find the relationship between idle load and utilization-energy consumption relationship interesting. I see two ways this can be addressed. 

1. Let's assume we have a perfect way of modelling the utilization-energy consumption based on for example CPU usage. Then we can perfectly map out which processes account for which energy consumption and what ever of the total energy consumption is left is the idle load consumption. Attributing this idle energy consumption to the owner of the hardware, especially if this is a cloud vendor, could incentivize them to improve how their load shifting to minimize the amount of machines standing idle. And over time this could lead to a reduction of HW purchases because the existing HW can handle higher volumes, which is a reduction in embodied carbon.
 
2. Let's assume we do NOT have a perfect way of modeling the  utilization-energy consumption. Then we have the option to look at the servers total energy consumption and try to assign the consumption to different processes running on said server, disregarding the time the machine was idle. This may be the easiest first step, but is can also make it harder to see the effect of any software changes I do if my hardware is managed by someone else.

As for utilization-energy consumption based on a single metric, like CPU, it tends to only work well for high utilization rates due to the energy proportionality aspect of servers. To clarify, if my server is consuming X kWh and process A is utilizing 15% of the CPU and then increases it to 20%, that does not necessarily mean my server will now consume (X*1,05) kWh.

**Comment by jawache** [comment]
This is a great question, we need to help people trying to implement the SCI decide how to calculate their `E`. The SCI should define just the requirements and constraints of `E` and allow anyone implementing the SCI the flexibility apply it to their probably very unique use case and situation. I.e. steering clear of implementation details is a safe thing to do in terms of the spec.

- One requirement we've discussed is that it's measured in kWh.
- Another requirement is that It must measure all the energy from within the software boundary (we need to define the software boundary in a separate issue. That discussion is where we should decide if idle machines are included in the software boundary, also what peripherals of a machine need to be included, the display?)
- Another constraint is that it needs to be bucketed using the same methodology as `I`, e.g. if, for `I` you are using 5 mins real-time CI data for every region, you'll also need to measure and aggregate the energy consumption of your application in the same 5 min slots. If you are using yearly regional averages for `I` then `E` needs to be measured and aggregated in the same regional buckets. This is so the `E` * `I` part of the question makes sense.

Another requirement based on the conversation above is do we insist on direct measurement or modelling? If we allow models, like a utilisation based model, then what are the requirements of those models?

**Comment by atg-abhishek** [comment]
**From the meeting:**

@jawache : we want to stay away from implementation recommendations; if there are 2 ways to implement the methodology then we are _safe_ from patent issues. there is direct measurement through the meter, or everything else is a model? if we assume everything else is a model, do we want to have some requirements for the model?

@Henry-WattTime : you should include everything of significance based on tools that they have access to ; you determine what is included in the software boundary #56 and provide justification for it ; the boundary means what does your software depends on ; 

@SaraEmilyBergman : we might want to think about what happens when we have shared hardware; there are some fundamental constraints like power consumption can't exceed the input power 

@dtoakley : there are datasets that provide figures for 0% utilization and 100% utilization 

@vaughnknight : a calculator is at the end of the day a model; 

what we have described is touching on the concept of software boundaries #56 - software boundary should include idle servers 

we also need to figure out what is "significant" in the first place ; @vaughnknight : but there might also be other significant components as well 

if we say you have to include idle machines and say it in a general enough way then that could help to address some of that here. so significance should include supporting infrastructure like DBs, ... we need to make sure we use the right term MUST or SHOULD 

@Henry-WattTime @vaughanknight and @dtoakley will make a PR to address this and #56
